api_platform:
    title: Stankoff.RU
    version: 4.2.12
    description: |
        Сайт Stankoff.RU
    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        multipart: ['multipart/form-data']
    docs_formats:
        jsonld: ['application/ld+json']
        html: ['text/html']
    http_cache:
        public: true
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    serializer:
        hydra_prefix: true
    oauth:
        enabled: true
        clientId: '%env(OIDC_SWAGGER_CLIENT_ID)%'
        pkce: true
        type: oauth2
        flow: authorizationCode
        tokenUrl: '%env(OIDC_SERVER_URL)%/protocol/openid-connect/token'
        authorizationUrl: '%env(OIDC_SERVER_URL)%/protocol/openid-connect/auth'
        scopes:
            openid: (required) Indicates that the application intends to use OIDC to verify the user's identity

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    # "name" is not a property, it's only a method "getName"
    # Can't apply ApiFilter PHP attribute on method, so declare filter manually
    app.filter.user.admin.name:
        class: 'App\Doctrine\Orm\Filter\NameFilter'
        arguments:
            $managerRegistry: '@doctrine'
            $logger: '@logger'
            $nameConverter: '@?api_platform.name_converter'
            $properties: { name: 'ipartial' }
        tags: [ 'api_platform.filter' ]
